# Generated by Django 3.0.5 on 2020-06-14 23:10

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import taggit.managers


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('taggit', '0003_taggeditem_add_unique_index'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('comment_id', models.AutoField(primary_key=True, serialize=False)),
                ('comment_text', models.TextField()),
                ('comment_date', models.DateField(auto_now_add=True)),
                ('comment_votes', models.IntegerField(default=0)),
                ('comment_author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comments', models.ManyToManyField(to='blr.Comment')),
            ],
        ),
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resource_name', models.CharField(max_length=100)),
                ('resource_description', models.TextField()),
                ('resource_author', models.CharField(max_length=50)),
                ('resource_image', models.ImageField(default='default.png', upload_to='')),
                ('resource_votes', models.IntegerField(default=0)),
                ('resource_url', models.URLField()),
                ('resource_price', models.DecimalField(decimal_places=2, default=0, max_digits=4)),
                ('resource_discount', models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(100)])),
                ('resource_creation_date', models.DateField(auto_now_add=True)),
                ('resource_slug', models.SlugField(max_length=100, unique=True)),
                ('post_author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='blr.Profile')),
                ('resource_tags', taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags')),
                ('resource_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blr.Type')),
            ],
        ),
        migrations.AddField(
            model_name='profile',
            name='resources',
            field=models.ManyToManyField(to='blr.Resource'),
        ),
        migrations.AddField(
            model_name='profile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='comment',
            name='resource_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blr.Resource'),
        ),
        migrations.AlterUniqueTogether(
            name='comment',
            unique_together={('comment_id', 'resource_id')},
        ),
    ]
