# Generated by Django 3.0.5 on 2020-06-14 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blr', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='type',
            name='type_name',
            field=models.CharField(choices=[('Book', 'Book'), ('Video', 'Video'), ('Blog', 'Blog')], max_length=20),
        ),
    ]
