# Generated by Django 3.0.5 on 2020-06-14 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blr', '0002_auto_20200615_0117'),
    ]

    operations = [
        migrations.AlterField(
            model_name='type',
            name='type_name',
            field=models.CharField(max_length=20),
        ),
    ]
