# Generated by Django 3.0.5 on 2020-05-03 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blr', '0002_auto_20200503_1903'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resource',
            name='resource_image',
            field=models.ImageField(upload_to='media/resource_img/'),
        ),
    ]
