# Generated by Django 3.0.5 on 2020-05-18 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blr', '0003_auto_20200503_1908'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resource',
            name='resource_image',
            field=models.ImageField(blank=True, null=True, upload_to='media/resource_img/'),
        ),
    ]
