# Generated by Django 3.0.5 on 2020-06-14 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blr', '0004_auto_20200615_0135'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='resources',
            field=models.ManyToManyField(to='blr.Resource'),
        ),
    ]
