# Generated by Django 3.0.5 on 2020-05-28 23:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blr', '0004_auto_20200519_0025'),
    ]

    operations = [
        migrations.RenameField(
            model_name='resource',
            old_name='post_autor',
            new_name='post_author',
        ),
    ]
