# Generated by Django 3.0.5 on 2020-06-14 23:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blr', '0005_profile_resources'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='resources',
        ),
    ]
