# Generated by Django 3.0.5 on 2020-06-07 08:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blr', '0007_resource_resource_tags'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resource',
            name='resource_category',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
