# Generated by Django 3.0.5 on 2020-06-07 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blr', '0008_auto_20200607_1025'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resource',
            name='resource_image',
            field=models.ImageField(default='media/resource_img/default.png', upload_to='media/resource_img/'),
        ),
    ]
