# Generated by Django 3.0.5 on 2020-06-15 17:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blr', '0008_auto_20200615_0244'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resource',
            name='post_author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='post_author', to='blr.Profile'),
        ),
        migrations.RemoveField(
            model_name='resource',
            name='resource_votes',
        ),
        migrations.AddField(
            model_name='resource',
            name='resource_votes',
            field=models.ManyToManyField(blank=True, related_name='votes', to='blr.Profile'),
        ),
    ]
