# Generated by Django 3.0.5 on 2020-06-16 08:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blr', '0009_auto_20200615_1927'),
    ]

    operations = [
        migrations.RenameField(
            model_name='resource',
            old_name='resource_votes',
            new_name='user_saved',
        ),
    ]
