# Generated by Django 3.0.5 on 2020-06-16 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blr', '0010_auto_20200616_1019'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='num_vote_down',
            field=models.PositiveIntegerField(db_index=True, default=0),
        ),
        migrations.AddField(
            model_name='resource',
            name='num_vote_up',
            field=models.PositiveIntegerField(db_index=True, default=0),
        ),
        migrations.AddField(
            model_name='resource',
            name='vote_score',
            field=models.IntegerField(db_index=True, default=0),
        ),
    ]
