# Generated by Django 3.0.5 on 2020-06-07 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blr', '0010_auto_20200607_1838'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resource',
            name='resource_image',
            field=models.ImageField(default='static/images/default.png', upload_to=''),
        ),
    ]
