# Generated by Django 3.0.5 on 2020-06-07 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blr', '0011_auto_20200608_0021'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resource',
            name='resource_image',
            field=models.ImageField(default='default.png', upload_to=''),
        ),
    ]
