# Generated by Django 3.0.5 on 2020-06-16 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blr', '0011_auto_20200616_1109'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='resource_stars',
            field=models.IntegerField(default=0),
        ),
    ]
