# Generated by Django 3.0.5 on 2020-06-18 00:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blr', '0012_resource_resource_stars'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
