# Generated by Django 3.0.5 on 2020-06-18 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blr', '0014_remove_resource_resource_discount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_pic',
            field=models.ImageField(blank=True, default='default/profile1.png', null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='resource',
            name='resource_image',
            field=models.ImageField(default='default/default.png', upload_to=''),
        ),
    ]
